Repository Pyxxil/upskill, pull requests merged in 2020-07, with the labels that each got.

#6 Rename Courses to Classes
  src/App.tsx
  src/pages/Book.tsx
  src/pages/Class.tsx
  src/pages/Classes.tsx
  src/pages/Course.tsx
  src/pages/Courses.tsx
Labels: enhancement

#18 Add Navbar
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  package.json
  yarn.lock
Labels: enhancement

#19 Remove Incorrect Lines
  frontend/src/App.tsx
Labels: bug

#22 Add Initial Card Components
  frontend/src/assets/test.webp
  frontend/src/components/Card.tsx
  frontend/src/components/Stars.tsx
  frontend/src/components/card.css
  frontend/src/index.css
  frontend/src/pages/Classes.tsx
  frontend/src/pages/Instructors.tsx
Labels: enhancement

#23 Instructor page
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/profiles/John Smith.jpg
  frontend/src/assets/profiles/Josh Hill 2.png
  frontend/src/assets/profiles/Josh Hill.jpg
  frontend/src/assets/profiles/Kimberley Evans-Parker.jpg
  frontend/src/assets/profiles/Ryan Tan.png
  frontend/src/assets/profiles/Sunny Feng.jpg
  frontend/src/components/Card.tsx
  frontend/src/components/card.css
  frontend/src/pages/Instructor.css
  frontend/src/pages/Instructor.tsx
  frontend/src/pages/Instructors.tsx
  frontend/yarn.lock
  lerna.json
  package.json
  yarn.lock
Labels: enhancement

#24 Modify Class Page
  frontend/src/App.tsx
  frontend/src/pages/Book.tsx
  frontend/src/pages/Class.tsx
Labels: enhancement

#31 Hack Together a Booking Page
  frontend/package.json
  frontend/src/pages/Book.tsx
  frontend/yarn.lock
Labels: enhancement

#34 Content
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/classes/AI.jpeg
  frontend/src/assets/classes/Blockchain.jpeg
  frontend/src/assets/classes/ICT.jpg
  frontend/src/assets/classes/binary.jpg
  frontend/src/assets/classes/idea.jpg
  frontend/src/assets/classes/money.jpg
  frontend/src/assets/classes/networking.jpg
  frontend/src/assets/classes/programming.png
  frontend/src/assets/classes/purple comp.jpg
  frontend/src/assets/classes/rainbow brain.jpeg
  frontend/src/assets/classes/social setcurity.jpg
  frontend/src/assets/classes/start-up.jpg
  frontend/src/assets/profiles/Hassaan Mirza.jpg
  frontend/src/assets/profiles/Josh Hill 2.png
  frontend/src/assets/profiles/Ryan Tan 2.png
  frontend/src/assets/profiles/Terrence Qu.jpg
  frontend/src/components/Card.tsx
  frontend/src/components/card.css
  frontend/src/pages/Classes.tsx
  frontend/src/pages/Instructor.css
  frontend/src/pages/Instructor.tsx
  frontend/src/pages/Instructors.tsx
  frontend/src/pages/Landing.css
  frontend/src/pages/Landing.tsx
Labels: enhancement

#40 Enhancment/styling
  backend/passportConfig.js
  backend/routes/userRoutes.js
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/profiles/Josh Hill.jpg
  frontend/src/assets/profiles/Josh Hill.png
  frontend/src/assets/profiles/Terence Qu.jpg
  frontend/src/assets/rewards/unicef-logo.png
  frontend/src/components/Card.tsx
  frontend/src/components/card.css
  frontend/src/index.css
  frontend/src/pages/Book.tsx
  frontend/src/pages/Classes.tsx
  frontend/src/pages/CompanyChallenge.tsx
  frontend/src/pages/CompanyChallenges.tsx
  frontend/src/pages/Instructor.css
  frontend/src/pages/Instructor.tsx
  frontend/src/pages/Instructors.tsx
  frontend/src/pages/Landing.css
  frontend/src/pages/Landing.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/Rewards.tsx
  frontend/src/pages/book.css
  frontend/src/utils/userRequests.tsx
Labels: enhancement

#41 Add logo and favicon
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/logo.PNG
Labels: enhancement

#46 Documentation/readme
  README.md
  readmeImages/finalSlideDEVS.PNG
  readmeImages/groupPhoto.jpg
Labels: documentation, enhancement
